// Dicionário de todos os textos da app. Partilhado pelo browser (window.TEXTOS_DEF) e pelo servidor (require).
// Cada linha: [chave, rótulo no admin, valor por omissão, variáveis disponíveis (opcional)].
// Um valor que é uma lista (array) tem várias alternativas; a app sorteia uma de cada vez.
// Nos textos: **negrito**; {variável}; variáveis que acabam em «Html» entram sem escape (só as passa o código).
(function (raiz) {
  const GRUPOS = [];
  const G = (nome, linhas) => GRUPOS.push({ nome, linhas });

  G('Geral', [
    ['app.nome', 'Nome da app (cabeçalho, separador, ícone)', 'Tarefas Porto'],
    ['app.emoji', 'Emoji ao lado do nome', '🏠'],
    ['app.nomeCurto', 'Nome curto (ícone do ecrã principal)', 'Tarefas'],
    ['app.descricao', 'Descrição da app', 'Tarefas domésticas do T2'],
    ['nav.hoje', 'Separador 1', 'Hoje'], ['nav.hoje.i', 'Ícone do separador 1', '☀️'],
    ['nav.semana', 'Separador 2', 'Semana'], ['nav.semana.i', 'Ícone do separador 2', '📅'],
    ['nav.rot', 'Separador 3', 'Rotações'], ['nav.rot.i', 'Ícone do separador 3', '🔄'],
    ['nav.tarefas', 'Separador 4', 'Tarefas'], ['nav.tarefas.i', 'Ícone do separador 4', '📝'],
    ['nav.mais', 'Separador 5', 'Definições'], ['nav.mais.i', 'Ícone do separador 5', '⚙️'],
    ['filtro.todos', 'Filtro: todas as pessoas', 'Todos'],
    ['filtro.aria', 'Filtro: descrição para leitores de ecrã', 'Filtrar por pessoa'],
    ['tag.opcional', 'Etiqueta de tarefa opcional', 'se necessário'],
    ['tag.trocado', 'Etiqueta de responsável trocado', 'trocado'],
    ['tag.atual', 'Etiqueta «atual»', 'atual'],
    ['linha.feitoHoje', 'Descrição da caixa «feito hoje»', 'Feito hoje'],
    ['linha.verDias', 'Descrição do contador de dias', 'Ver os dias'],
    ['lixo.titulo', 'Nome da tarefa do lixo', 'Levar o lixo'],
    ['lixo.emoji', 'Emoji do lixo', '🗑️'],
    ['tempo.agora', 'Tempo: agora', 'agora mesmo'],
    ['tempo.min', 'Tempo: minutos', 'há {n} min', '{n}'],
    ['tempo.h', 'Tempo: horas', 'há {n} h', '{n}'],
    ['tempo.d', 'Tempo: dias', 'há {n} d', '{n}'],
  ]);
  G('Dias e frequências', [
    ...['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'].map((d, i) => ['dia.l' + i, 'Dia ' + (i + 1) + ' (nome completo)', d]),
    ...['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'].map((d, i) => ['dia.c' + i, 'Dia ' + (i + 1) + ' (abreviado; a inicial vai nas bolinhas)', d]),
    ['freq.daily', 'Frequência: diária', 'Diária'],
    ['freq.w2', 'Frequência: 2 vezes por semana', '2x por semana'],
    ['freq.w1', 'Frequência: 1 vez por semana', '1x por semana'],
    ['freq.need', 'Frequência: conforme necessário', 'Conforme necessário'],
    ['freq.wday', 'Frequência: dia fixo (na lista de escolha)', 'Semanal em dia fixo'],
    ['freq.once', 'Frequência: uma vez (na lista de escolha)', 'Uma vez'],
    ['freq.wdayEm', 'Frequência: dia fixo (na lista de tarefas)', 'Semanal ({dia})', '{dia}'],
    ['freq.onceEm', 'Frequência: uma vez (na lista de tarefas)', 'Uma vez em {data}', '{data}'],
    ['quem.rota', 'Quem faz: rotação da divisão', 'rotação da divisão'],
    ['quem.quartos', 'Quem faz: ocupantes do quarto', 'ocupantes do quarto'],
    ['quem.todos', 'Quem faz: todos', 'todos'],
    ['quem.rodar', 'Quem faz: rotativo', 'rotativo'],
  ]);
  G('Página Hoje', [
    ['hoje.cabecalho', 'Cabeçalho do dia', '{dia}, {data} · Semana {n} da rotação', '{dia} {data} {n}'],
    ['hoje.feitas', 'Contador de tarefas feitas', '{d}/{n} feitas', '{d} {n}'],
    ['hoje.lixo', 'Aviso de quem leva o lixo hoje', '{emoji} Hoje o lixo é de {nomeHtml}.', '{emoji} {nomeHtml}'],
    ['hoje.tituloHoje', 'Secção «Hoje»', 'Hoje'],
    ['hoje.tituloSemana', 'Secção «Esta semana»', 'Esta semana'],
    ['hoje.vazio', 'Quando não há tarefas hoje', 'Sem tarefas para hoje 🎉'],
  ]);
  G('Página Semana', [
    ['semana.anterior', 'Botão semana anterior (descrição)', 'Semana anterior'],
    ['semana.seguinte', 'Botão semana seguinte (descrição)', 'Semana seguinte'],
    ['semana.voltarHoje', 'Botão para voltar à semana atual', 'Hoje'],
    ['semana.rotulo', 'Rótulo da semana', 'Semana {n}', '{n}'],
    ['semana.atual', 'Rótulo da semana atual', 'Semana {n} · atual', '{n}'],
    ['semana.responsaveis', 'Caixa «Responsáveis da semana»', 'Responsáveis da semana'],
    ['semana.trocar', 'Sugestão «trocar»', '· trocar'],
    ['semana.responsavel', 'Lista de responsável (descrição)', 'Responsável'],
    ['semana.responsavelPor', 'Cartão: responsável por', 'Responsável por: **{divisoes}**', '{divisoes}'],
    ['semana.semDivisao', 'Cartão: sem divisão comum', 'Sem divisão comum'],
    ['semana.quartoInd', 'Cartão: quarto individual', 'quarto individual'],
    ['semana.quartoPart', 'Cartão: quarto partilhado', 'quarto partilhado'],
    ['semana.nadaAtribuido', 'Cartão vazio', 'Nada atribuído'],
    ['semana.subInd', 'Nota do quarto individual', 'Quarto individual'],
    ['semana.subPartilhado', 'Nota do quarto partilhado', 'Quarto partilhado com {nome}', '{nome}'],
  ]);
  G('Página Rotações', [
    ['rot.areasTitulo', 'Título das áreas comuns', 'Áreas comuns — rotação de 3 semanas'],
    ['rot.areasNota', 'Nota das áreas comuns', 'Linha destacada = semana atual. Depois da Semana 3 volta à Semana 1.'],
    ['rot.quartosTitulo', 'Título dos quartos', 'Quartos — rotação mensal'],
    ['rot.colMes', 'Coluna: mês', 'Mês'],
    ['rot.colInd', 'Coluna: quarto individual', 'Quarto individual'],
    ['rot.colPart', 'Coluna: quarto partilhado', 'Quarto partilhado (conjunto)'],
    ['rot.quartosNota', 'Nota dos quartos', 'A sequência repete-se de 3 em 3 meses. Cada pessoa limpa o quarto que ocupa nesse mês; no partilhado os dois ocupantes são responsáveis.'],
    ['rot.lixoTitulo', 'Título do lixo', 'Lixo — de 2 em 2 dias'],
  ]);
  G('Página Tarefas', [
    ['sub.lista', 'Separador: lista', 'Tarefas'],
    ['sub.stats', 'Separador: estatísticas', 'Estatísticas'],
    ['sub.ativ', 'Separador: atividade', 'Atividade'],
    ['tarefas.titulo', 'Título da lista', 'Tarefas'],
    ['tarefas.contagem', 'Contagem de tarefas', '{a} ativas de {n}', '{a} {n}'],
    ['tarefas.nova', 'Botão nova tarefa', '+ Nova tarefa'],
    ['tarefas.procurarPh', 'Caixa de procura', ['Procurar tarefa…', 'Procurar tarefa (ou uma boa desculpa)…', 'O que é que andas a evitar?…']],
    ['tarefas.procurarAria', 'Caixa de procura (descrição)', 'Procurar tarefa'],
    ['tarefas.todas', 'Filtro: todas as divisões', 'Todas'],
    ['tarefas.restaurar', 'Botão restaurar originais', 'Restaurar tarefas originais'],
    ['tarefas.nenhuma', 'Nenhuma tarefa encontrada', ['Nenhuma tarefa encontrada. Talvez tenha fugido 🏃', 'Nada por aqui. Suspeito e suspeitamente limpo 🕵️', 'Zero tarefas. Aproveita antes que alguém invente mais 🤫']],
    ['tarefas.estaSemana', 'Quem faz esta semana', 'esta semana: **{nomes}**', '{nomes}'],
    ['tarefas.pausar', 'Botão pausar', 'Pausar'],
    ['tarefas.ativar', 'Botão ativar', 'Ativar'],
    ['tarefas.editar', 'Botão editar', 'Editar'],
    ['stats.ultimas', 'Estatísticas: últimas 4 semanas', 'Últimas 4 semanas · {d}/{n}', '{d} {n}'],
    ['stats.nota90', 'Nota a partir de 90 %', ['Máquina de limpar 🏆', 'Alerta: excesso de brilho ✨', 'Já pode dar aulas de esfregona 🎓']],
    ['stats.nota70', 'Nota a partir de 70 %', ['Ritmo de campeão 💪', 'A casa agradece, o pó tem medo 😤', 'Dá gosto ver 👏']],
    ['stats.nota40', 'Nota a partir de 40 %', ['Vai andando, vai andando 🚶', 'Nem oito nem oitenta, mas honesto 🤷', 'A meio do caminho entre herói e sofá 🛋️']],
    ['stats.nota15', 'Nota a partir de 15 %', ['A aquecer os motores 🔥', 'Está quase, só falta começar 😅', 'A pensar seriamente em fazer algo 🤔']],
    ['stats.nota0', 'Nota abaixo de 15 %', ['Precisa de café ☕', 'Encontrado em paradeiro incerto 🔍', 'A poupar energia para o futuro 🔋']],
    ['stats.explicacao', 'Explicação da percentagem', 'A percentagem conta as tarefas atribuídas a cada pessoa (com trocas incluídas). A semana atual ainda tem dias por vir.'],
    ['stats.atraso', 'Título «Em atraso»', 'Em atraso'],
    ['stats.maisN', 'Mais itens em atraso', 'E mais {n}…', '{n}'],
    ['stats.nadaAtraso', 'Nada em atraso', ['Nada em atraso. Casa a brilhar ✨🎉', 'Nada em atraso. Quem são estas pessoas e o que fizeram aos preguiçosos? 😳', 'Tudo em dia. A Marie Kondo mandou cumprimentos 🧘']],
    ['stats.diarias', 'Diárias por marcar', 'Diárias por marcar: '],
    ['stats.rodape', 'Rodapé das estatísticas', 'Só entram semanas desde a «Semana 1» das Definições.'],
    ['ativ.titulo', 'Título da atividade', 'Atividade recente'],
    ['ativ.carregar', 'A carregar a atividade', 'A carregar…'],
    ['ativ.vazio', 'Atividade vazia', ['Silêncio total 🦗 Alguém tem de fazer alguma coisa! (ou estás sem ligação ao servidor)', 'Aqui reina a paz… e o pó 😌 (ou não tens ligação ao servidor)', 'Nada a reportar. O que é suspeito numa casa de três 🕵️']],
  ]);
  G('Extras divertidos', [
    ['desculpa.titulo', 'Gerador de desculpas: título', 'Desculpa do dia 🎭'],
    ['desculpa.botao', 'Gerador de desculpas: botão', 'Outra desculpa'],
    ['desculpa.nota', 'Gerador de desculpas: aviso', 'Uso por conta e risco de quem a ouvir.'],
    ['desculpa.lista', 'Gerador de desculpas: as desculpas', [
      'Ia limpar, mas o pó pediu privacidade.', 'Estou em greve de esfregona por tempo indeterminado ✊', 'O chão está apenas a fazer um projeto de arte contemporânea 🎨',
      'Juro que a loiça estava limpa há cinco minutos.', 'A minha esponja pediu baixa médica 🤒', 'Estava a poupar água, pelo planeta 🌍',
      'Mercúrio está retrógrado, não se limpa nada em Mercúrio retrógrado ♏', 'O aspirador olhou para mim de lado e perdi a confiança 🥺',
      'Ia fazer, mas primeiro tenho de me organizar. Para isso preciso de dormir 😴', 'A casa de banho está em fase de decomposição criativa.',
      'Vi um tutorial sobre como limpar. Conta como ter limpado.', 'Amanhã faço a dobrar. (Isto vale desde 2019.)', 'O lixo é que se recusou a sair de casa 🗑️',
      'Estava à espera que a loiça se lavasse por osmose.', 'Foi o cão. (Não temos cão.) 🐕', 'Cansei-me só de olhar para a lista 😮‍💨',
      'Delegar é uma forma de liderança 🧠', 'O pó já cá estava primeiro. É património.', 'Tinha a agenda cheia de sofá 🛋️', 'Limpei mentalmente. Foi intenso 🧘']],
    ['stats.lider', 'Estatísticas: quem lidera', ['👑 {nome} lidera com {pct}% — {titulo}', '🏆 {nome} está imparável ({pct}%): {titulo}', '🥇 {nome} ({pct}%) — {titulo}'], '{nome} {pct} {titulo}'],
    ['stats.titulos', 'Estatísticas: títulos honoríficos de quem lidera', ['Lenda da loiça', 'Poder absoluto da esponja', 'Domínio total do pó', 'Força da natureza (da limpa)', 'Génio da vassoura', 'Entidade suprema do esfregão']],
    ['stats.lanterna', 'Estatísticas: quem está mais atrás (deixa vazio para não aparecer)', ['{nome} está em modo poupança de energia 🔋', '{nome} tem andado a estudar o sofá com muito rigor 🛋️', '{nome} guarda forças para uma grande limpeza (um dia) 💤'], '{nome}'],
    ['dlg.tituloPh', 'Diálogo: exemplo no campo da tarefa', ['Ex.: Lavar a loiça', 'Ex.: Convencer o Francisco a lavar a loiça', 'Ex.: Fingir que não vi a loiça']],
    ['dlg.notaPh', 'Diálogo: exemplo no campo da nota', ['Ex.: se ninguém fizer, faço eu (mentira)', 'Ex.: com luvas, por favor 🧤', 'Ex.: sem música alta às 7h da manhã']],
    ['egg.msg', 'Segredo: mensagens', ['Segredo descoberto! O pó treme à tua passagem 🧹', 'Modo Marie Kondo ativado: isto dá-te alegria? ✨', 'Parabéns! Ganhaste absolutamente nada. Mas com estilo 🎉', 'A esponja reconhece o teu valor 🧽', 'Nível desbloqueado: Mestre do Detergente 🫧']],
    ['egg.emojis', 'Segredo: emojis que caem', '🧽🧹🧼🫧✨🧻🪣🎉'],
    ['sobre.rodape', 'Definições: rodapé', ['Feito com ☕ e pouco respeito pelo pó.', 'Nenhum esfregão foi maltratado neste projeto 🧽', 'Se chegaste aqui, já procuraste demais. Carrega 7 vezes na versão 👀', 'Contém vestígios de humor duvidoso.']],
  ]);
  G('Efeitos e easter eggs', [
    ['fx.emojisTarefa', 'Chuva ao concluir uma tarefa: emojis', '💅💅🏻💅🏽💅🏿✨💖🌈💄👠🪩🎀'],
    ['fx.emojisDia', 'Chuva ao completar o dia: emojis', '💅💅🏻💅🏼💅🏽💅🏾💅🏿✨💖🌈👑💃🪩🦄🏳️‍🌈'],
    ['fx.emojisTudo', 'Chuva ao completar TUDO: emojis', '🏳️‍🌈🏳️‍⚧️💅💅🏻💅🏽💅🏿🌈👑💃🕺🪩💖✨🦄💄👠🎀🔥💋'],
    ['fx.emojisSemana', 'Chuva ao completar a semana: emojis', '🏳️‍🌈💅🌈👑🪩💃🦄✨💖🔥💎🏆'],
    ['fx.relogio', 'Emojis que abanam de cada lado do texto (sorteia-se um para cada lado)', ['💅', '💅🏻', '💅🏽', '💅🏿', '💃', '👑', '🦄', '🌈', '💖', '🪩']],
    ['fx.clock', 'Texto ao completar o dia', 'CLOCK IIIIIT'],
    ['fx.tudo', 'Texto ao completar TUDO (por baixo do anterior)', 'ZERO DESCULPAS. LENDÁRIO. 🗿'],
    ['fx.semana', 'Texto ao completar a semana toda', 'LOCKED IN 🔒 SEMANA COMPLETA'],
    ['fx.combo3', 'Combo: 3 tarefas seguidas', 'COMBO x3 🔥'],
    ['fx.combo5', 'Combo: 5 tarefas seguidas', 'PARA. ESTÁS A ASSUSTAR-NOS 😨'],
    ['fx.combo8', 'Combo: 8 tarefas seguidas', 'ISTO JÁ É CRIME 🚨'],
    ['fx.desmarcou', 'Ao desmarcar uma tarefa (de vez em quando)', ['Desmarcou? Cringe 😬', 'Arrependimento em 3… 2… 1… 📉', 'Ah, era mentira? Clássico 🤡', 'Skill issue 💀', 'Tens a certeza? Ninguém te viu a fazer 👀']],
    ['fx.noite', 'Tarefa concluída de madrugada (de vez em quando)', ['{hora}h?? Vai dormir, personagem secundária 🧟', 'A esfregar às {hora}h? Isto é vício 🌙', 'Ninguém limpa às {hora}h. Nem os vilões 🦇']],
    ['fx.marcos', 'Marcos de tarefas concluídas (uma linha por marco: número|texto)', ['10|10 tarefas. Já deu para aquecer 🔥', '50|50 tarefas. Isto já é rotina, não hobby 🫠', '100|100 TAREFAS. Podias ter arranjado um emprego 💼', '250|250. Chama-se dependência e chama-se limpar 🧽', '500|500. Vives num anúncio de detergente 🫧']],
    ['fx.procura', 'Pesquisa de tarefas: respostas a gozar (uma linha por resposta: palavra|resposta)', ['sofá|Sofá não é tarefa. Sofá é estilo de vida 🛋️ (bela tentativa)', 'sofa|Sofá não é tarefa. Sofá é estilo de vida 🛋️ (bela tentativa)', 'netflix|Netflix não conta como tarefa. Nem como personalidade 📺', 'dormir|Dormir não é tarefa. Mas é a tua favorita 😴', 'preguiça|Preguiça não está na lista. Mas tens um cargo honorário 🦥', 'nada|«Nada» já tem muito de ti. Não está na lista 🕳️', 'férias|Férias não entram em tarefas. Sonhar acordado também não ☀️', 'desculpa|Aqui não vendemos desculpas. (Vai às Estatísticas 🤫)']],
    ['fx.logo', 'Segredo: 5 toques no título da app', 'SIGMA GRINDSET 🐺'],
    ['fx.logoEmojis', 'Segredo do título: emojis', '🗿🐺💪🔥'],
  ]);
  G('Diálogo de tarefa', [
    ['dlg.nova', 'Título: nova tarefa', 'Nova tarefa'],
    ['dlg.editar', 'Título: editar tarefa', 'Editar tarefa'],
    ['dlg.tarefa', 'Campo: tarefa', 'Tarefa'],
    ['dlg.divisao', 'Campo: divisão', 'Divisão / categoria'],
    ['dlg.responsavel', 'Campo: responsável', 'Responsável'],
    ['dlg.optRota', 'Opção: rotação da divisão', 'Rotação da divisão (só Cozinha, Sala, Casa de banho)'],
    ['dlg.optQuartos', 'Opção: ocupantes do quarto', 'Ocupantes do quarto (mensal)'],
    ['dlg.optTodos', 'Opção: todos', 'Todos'],
    ['dlg.optRodar', 'Opção: rotativo', 'Rotativo (muda de pessoa todas as semanas)'],
    ['dlg.frequencia', 'Campo: frequência', 'Frequência'],
    ['dlg.data', 'Campo: data', 'Data'],
    ['dlg.diaSemana', 'Campo: dia da semana', 'Dia da semana'],
    ['dlg.nota', 'Campo: nota', 'Nota (opcional)'],
    ['dlg.apagar', 'Botão apagar', 'Apagar'],
    ['dlg.duplicar', 'Botão duplicar', 'Duplicar'],
    ['dlg.cancelar', 'Botão cancelar', 'Cancelar'],
    ['dlg.guardar', 'Botão guardar', 'Guardar'],
    ['dlg.confirmarApagar', 'Botão apagar (confirmação)', 'Confirmar apagar'],
    ['dlg.copia', 'Sufixo de uma tarefa duplicada', ' (cópia)'],
    ['dlg.erroRota', 'Erro: rotação numa divisão inválida', 'A «Rotação da divisão» só existe para Cozinha, Sala e Casa de banho. Escolhe uma pessoa ou «Todos».'],
  ]);
  G('Definições', [
    ['mais.pessoas', 'Título: pessoas', 'Pessoas'],
    ['mais.pessoasNota', 'Nota: pessoas', 'Mudar um nome muda para toda a gente.'],
    ['mais.pessoaN', 'Rótulo do campo de cada pessoa', 'Pessoa {n}', '{n}'],
    ['mais.rotacao', 'Título: rotação', 'Rotação'],
    ['mais.semana1', 'Campo: Semana 1', 'Segunda-feira da «Semana 1» (as semanas 2 e 3 seguem-se, e repete)'],
    ['mais.mesQuartos', 'Campo: mês de partida dos quartos', 'Mês de partida do quarto individual (é da 1.ª pessoa; depois roda 1 pessoa por mês)'],
    ['mais.incluirLixo', 'Opção: incluir o lixo', 'Incluir o lixo (seg, qua, sex, dom)'],
    ['mais.aparencia', 'Título: aparência', 'Aparência'],
    ['tema.auto', 'Tema automático', 'Automático'],
    ['tema.claro', 'Tema claro', 'Claro'],
    ['tema.escuro', 'Tema escuro', 'Escuro'],
    ['mais.sinc', 'Título: sincronização', 'Sincronização'],
    ['mais.sincAgora', 'Botão sincronizar', 'Sincronizar agora'],
    ['sinc.local', 'Estado: modo local', 'Modo local: sem servidor, as alterações ficam só neste aparelho.'],
    ['sinc.fila1', 'Estado: 1 alteração por enviar', '1 alteração por enviar'],
    ['sinc.filaN', 'Estado: várias alterações por enviar', '{n} alterações por enviar', '{n}'],
    ['sinc.semRedeFila', 'Estado: sufixo sem ligação', ' — sem ligação, seguem quando voltar.'],
    ['sinc.semRede', 'Estado: sem ligação', 'Sem ligação ao servidor. A app funciona com o que tem.'],
    ['sinc.ok', 'Estado: sincronizado', ['Sincronizado {quando} ✨', 'Tudo em sintonia {quando} 🎶', 'Nem um pó de diferença ({quando}) 🧹'], '{quando}'],
    ['sinc.nunca', 'Estado: ainda não sincronizou', 'Ainda não sincronizou.'],
    ['mais.dados', 'Título: dados', 'Dados'],
    ['mais.dadosNota', 'Nota: dados', 'As tarefas, marcações e definições são partilhadas por todos os aparelhos e atualizam sozinhas ({n} marcações). Exportar/Importar serve de cópia de segurança. **Atenção:** limpar, repor e importar afetam toda a gente.', '{n}'],
    ['mais.exportar', 'Botão exportar', 'Exportar'],
    ['mais.importar', 'Botão importar', 'Importar'],
    ['mais.limpar', 'Botão limpar marcações', 'Limpar marcações'],
    ['mais.repor', 'Botão repor tudo', 'Repor tudo'],
    ['mais.confirmarLimpar', 'Confirmação de limpar', 'Confirmar?'],
    ['mais.confirmarRepor', 'Confirmação de repor', 'Apagar tudo? Clica de novo'],
    ['mais.ficheiroInvalido', 'Erro: ficheiro inválido', 'Ficheiro inválido.'],
    ['ajuda.titulo', 'Título: como funciona', 'Como funciona'],
    ['ajuda.b1', 'Ajuda: linha 1', '**Hoje**: o que tens para fazer hoje. Escolhe o teu nome no topo e a app lembra-se.'],
    ['ajuda.b2', 'Ajuda: linha 2', '**Semana**: um cartão por pessoa; nas tarefas diárias marcas hoje e o contador abre os outros dias.'],
    ['ajuda.b3', 'Ajuda: linha 3', '**Rotações**: quem faz cada divisão, os quartos do mês e o lixo.'],
    ['ajuda.b4', 'Ajuda: linha 4', '**Tarefas**: cria, edita ou pausa tarefas; vê estatísticas e a atividade recente.'],
    ['ajuda.b5', 'Ajuda: linha 5', 'Tudo é partilhado: o que uma pessoa marca aparece aos outros em poucos segundos. Sem rede, as alterações ficam guardadas e seguem quando voltar a ligação.'],
    ['sobre.titulo', 'Título: sobre', 'Sobre'],
    ['sobre.linha', 'Linha da versão', '{app} · versão {versao} · sem bugs conhecidos (os desconhecidos estão a esconder-se) 🐛', '{app} {versao}'],
    ['sobre.atualizar', 'Botão procurar atualização', 'Procurar atualização'],
  ]);
  G('Avisos (Desfazer)', [
    ['toast.desfazer', 'Botão desfazer', 'Desfazer'],
    ['toast.apagada', 'Tarefa apagada', ['Tarefa apagada — adeus, até nunca 👋', 'Tarefa apagada. Era importante? Nunca saberemos 🤷', 'Puf! Desapareceu como as minhas meias 🧦']],
    ['toast.limpas', 'Marcações limpas', ['Marcações limpas — folha em branco ✨', 'Tudo por fazer outra vez. Boa sorte 🫡', 'Reset feito. A culpa volta ao zero 😇']],
    ['toast.repostas', 'Tudo reposto', ['Tudo reposto — como se nada fosse 🧼', 'Big bang! Começámos tudo de novo 💥', 'Casa nova, vida nova 🏡']],
    ['toast.duplicada', 'Tarefa duplicada', ['Tarefa duplicada — agora há duas 👯', 'Clonagem bem-sucedida. Ninguém pediu 🐑', 'Duas por uma. Os astros não perdoam ✨']],
    ['toast.restauradas1', 'Restaurada 1 tarefa original', '1 tarefa original de volta 🎩'],
    ['toast.restaurasN', 'Restauradas várias tarefas originais', '{n} tarefas originais de volta 🎩', '{n}'],
    ['toast.nadaRestaurar', 'Nada a restaurar', ['Já tens todas as originais. Nada a restaurar! 🙌', 'Estão todas cá. Nem uma se safou 😏']],
  ]);
  G('Instalar a app e acesso', [
    ['gate.titulo', 'Instalar: título', 'Instala a app para continuar'],
    ['gate.lead', 'Instalar: explicação', 'A {app} só funciona depois de adicionada ao ecrã principal.', '{app}'],
    ['gate.instalarAgora', 'Instalar: botão (Android)', 'Instalar agora'],
    ['gate.ios1', 'iPhone: passo 1', 'Toca no botão **Partilhar** (o quadrado com a seta para cima) na barra do Safari.'],
    ['gate.ios2', 'iPhone: passo 2', 'Desce e escolhe **Adicionar ao Ecrã Principal**, e depois **Adicionar**.'],
    ['gate.ios3', 'iPhone: passo 3', 'Fecha o Safari e abre a app **{nomeCurto}** pelo ícone que apareceu no ecrã principal.', '{nomeCurto}'],
    ['gate.iosNota', 'iPhone: nota', 'Se estiveres noutro browser que não o Safari, abre este endereço no Safari.'],
    ['gate.and1', 'Android: passo 1', 'Abre o menu do Chrome (os três pontos ⋮).'],
    ['gate.and2', 'Android: passo 2', 'Escolhe **Instalar app** (ou **Adicionar ao ecrã principal**).'],
    ['gate.and3', 'Android: passo 3', 'Abre a app **{nomeCurto}** pelo ícone que apareceu no ecrã principal.', '{nomeCurto}'],
    ['acesso.pendenteT', 'Aparelho pendente: título', 'À espera de aprovação'],
    ['acesso.pendenteTxt', 'Aparelho pendente: texto', 'O administrador ainda tem de aprovar este aparelho. Esta página atualiza sozinha.'],
    ['acesso.bloqueadoT', 'Aparelho bloqueado: título', 'Acesso bloqueado'],
    ['acesso.bloqueadoTxt', 'Aparelho bloqueado: texto', 'Este aparelho não tem acesso. Se achas que é engano, fala com o administrador.'],
    ['acesso.verificar', 'Botão verificar agora', 'Verificar agora'],
  ]);
  G('Notificações (ecrãs)', [
    ['push.titulo', 'Definições: título', 'Notificações'],
    ['push.explica', 'Definições: explicação', 'Recebe um aviso quando te passarem uma tarefa ou houver novidades.'],
    ['push.ativar', 'Botão ativar', 'Ativar notificações'],
    ['push.desativar', 'Botão desativar', 'Desativar neste aparelho'],
    ['push.testar', 'Botão enviar teste', 'Enviar notificação de teste'],
    ['push.estadoAtivas', 'Estado: ativas', 'Notificações ativas neste aparelho ✅'],
    ['push.estadoNegadas', 'Estado: bloqueadas no telemóvel', 'Bloqueaste as notificações. Ativa-as nas definições do telemóvel.'],
    ['push.estadoSemSuporte', 'Estado: sem suporte', 'Este aparelho não suporta notificações (no iPhone só funcionam na app instalada).'],
    ['push.estadoDesativadas', 'Estado: desativadas', 'Notificações desativadas neste aparelho.'],
    ['push.pedidoT', 'Pedido de ativação: título', 'Queres receber avisos?'],
    ['push.pedidoTxt', 'Pedido de ativação: texto', 'Avisamos-te quando te passarem uma tarefa e de manhã para não te esqueceres de nada.'],
    ['push.pedidoSim', 'Pedido de ativação: botão sim', 'Ativar'],
    ['push.pedidoNao', 'Pedido de ativação: botão não', 'Agora não'],
    ['push.testeEnviado', 'Aviso: teste enviado', ['Teste enviado — deves receber já uma notificação 📬', 'Pombo-correio largado 🕊️ Fica de olho no telemóvel']],
    ['push.erro', 'Aviso: erro ao ativar', 'Não foi possível ativar as notificações.'],
  ]);
  G('Notificações (mensagens enviadas)', [
    ['notif.novaTitulo', 'Tarefa nova: título', '{app}', '{app}'],
    ['notif.nova', 'Tarefa nova: texto', ['{quem} criou «{titulo}» {remate}', '{quem} descobriu mais uma: «{titulo}» {remate}', 'Nova missão de {quem}: «{titulo}» {remate}'], '{quem} {titulo} {remate}'],
    ['notif.trocaTitulo', 'Responsável trocado: título', '{app}', '{app}'],
    ['notif.troca', 'Responsável trocado: texto', ['{quem} passou-te {alvo} 😈', '{quem} confia em ti para {alvo} 🫡', 'Boa sorte com {alvo}, cortesia de {quem} 🎁'], '{quem} {alvo}'],
    ['notif.lembreteTitulo', 'Lembrete da manhã: título', ['Bom dia, {nome}! ☀️', 'Ei {nome}, a casa chama 📞', 'Acorda, {nome}! O pó não dorme 😴', '{nome}, hoje o sofá aguenta sem ti 🛋️'], '{nome}'],
    ['notif.lembrete', 'Lembrete da manhã: texto', ['Vê o que tens para hoje 🧹', 'A casa não se limpa sozinha (ainda) 🤖', 'Um bocadinho de cada vez e está feito ✨', 'Hoje é dia de ser herói da limpeza 🦸', 'Uma tarefinha e já podes dizer que trabalhaste 😌', 'A esponja está a olhar para ti 🧽👀', 'Estica-te, respira, esfrega 🧘'], ''],
    ['notif.testeTitulo', 'Teste: título', '{app}', '{app}'],
    ['notif.teste', 'Teste: texto', ['Funciona! 🎉 As notificações estão ligadas.', 'Funciona! 📣 Se leste isto, o pombo-correio chegou.', 'Funciona! ✅ Ninguém tem desculpa para não ver os avisos.']],
    ['notif.remateNova', 'Tarefa nova: remate', ['boa sorte, malta 🍀', 'vai ser um bom dia 😅', 'a lista cresceu 📈', 'ninguém está safo 😎', 'que comece o drama 🎭']],
  ]);
  G('Feed de atividade (servidor)', [
    ['act.alguem', 'Nome quando não se sabe quem foi', 'Alguém'],
    ['act.tarefaFallback', 'Nome quando a tarefa já não existe', 'tarefa'],
    ['act.marcou', 'Marcou uma tarefa', 'marcou «{titulo}»', '{titulo}'],
    ['act.desmarcou', 'Desmarcou uma tarefa', 'desmarcou «{titulo}»', '{titulo}'],
    ['act.limpou', 'Limpou as marcações', 'limpou todas as marcações'],
    ['act.trocaPara', 'Passou um responsável', 'passou {alvo} para {nome}', '{alvo} {nome}'],
    ['act.trocaRepor', 'Repôs um responsável', 'repôs o responsável de {alvo}', '{alvo}'],
    ['act.alvoLixo', 'Alvo: o lixo de um dia', 'o lixo de {data}', '{data}'],
    ['act.criou', 'Criou uma tarefa', 'criou a tarefa «{titulo}»', '{titulo}'],
    ['act.editou', 'Editou uma tarefa', 'editou a tarefa «{titulo}»', '{titulo}'],
    ['act.apagou', 'Apagou uma tarefa', 'apagou a tarefa «{titulo}»', '{titulo}'],
    ['act.semana1', 'Mudou a Semana 1', 'mudou a Semana 1 para {valor}', '{valor}'],
    ['act.mesQuartos', 'Mudou o mês dos quartos', 'mudou o mês de partida dos quartos para {valor}', '{valor}'],
    ['act.lixoOn', 'Ligou o lixo', 'ligou o lixo'],
    ['act.lixoOff', 'Desligou o lixo', 'desligou o lixo'],
    ['act.inicio', 'Lançou os dados iniciais', 'lançou os dados iniciais'],
    ['act.substituiu', 'Substituiu todos os dados', 'substituiu todos os dados'],
    ['act.nome', 'Mudou o nome de uma pessoa', 'mudou o nome da pessoa {n} para «{nome}»', '{n} {nome}'],
    ['act.nomesAdmin', 'O admin mudou os nomes', 'mudou os nomes das pessoas'],
    ['act.admin', 'Nome do admin no feed', 'Admin'],
    ['graca.marcou', 'Remates: marcou', ['despachado! 💪', 'que rapidez ⚡', 'ponto para o Porto 🏅', 'sem ninguém pedir (milagre) ✨', 'riscado da lista ✅', 'com um sorriso a brilhar ✨', 'lendário 🏅', 'a casa ficou mais feliz 🏡']],
    ['graca.desmarcou', 'Remates: desmarcou', ['afinal ainda não estava… 🤨', 'dúvidas existenciais 🤔', 'voltou atrás, acontece', 'a vida dá segundas oportunidades', 'o arrependimento bateu 😬', 'foi só um teste, certo? 🧪', 'plot twist 🎬']],
    ['graca.criou', 'Remates: criou', ['mais trabalho para toda a gente 😅', 'boa sorte, malta 🍀', 'ninguém pediu, mas cá está', 'a lista agradece (ou não)', 'lá vem mais uma 🙃', 'a criatividade não tem limites 🎨', 'e ninguém se ofereceu 🙈']],
    ['graca.editou', 'Remates: editou', ['ficou melhor, dizem ✨', 'retoques finais 🎨', 'só mais um bocadinho']],
    ['graca.apagou', 'Remates: apagou', ['já ninguém se lembra 🕊️', 'adeus, até nunca 👋', 'mandada para o lixo (o outro, não o de segunda) 🗑️', 'sem deixar rasto 🕵️', 'nunca existiu 🫥', 'que descanse em paz 🪦']],
    ['graca.troca', 'Remates: troca de responsável', ['boa sorte 😈', 'as trocas fazem-se 🤝', 'negócio fechado', 'é a vida 🤷', 'boa sorte, vais precisar 🍀', 'alguém está a fugir de responsabilidades 🏃']],
    ['graca.lixo', 'Remates: lixo ligado/desligado', ['o cheiro agradece 🌸', 'vamos ver quanto tempo aguenta 🙈']],
    ['graca.limpar', 'Remates: limpou marcações', ['folha em branco, respira fundo 🧼', 'como se nada fosse 🫧']],
    ['graca.inicio', 'Remates: dados iniciais', ['que comecem os jogos! 🎬', 'e pronto, está tudo a andar 🚀']],
    ['graca.nome', 'Remates: mudou um nome', ['crise de identidade? 🎭', 'novo nome, mesma tarefa 😎']],
    ['graca.config', 'Remates: definições', ['ajustes finos 🔧', 'a engenharia é uma arte 🛠️']],
  ]);

  const DEF = [];
  for (const g of GRUPOS) for (const [k, r, v, vars] of g.linhas) DEF.push({ k, g: g.nome, r, v, vars: vars || '', lista: Array.isArray(v) });
  const api = { DEF, GRUPOS: GRUPOS.map((g) => g.nome) };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else raiz.TEXTOS_DEF = DEF;
})(typeof window !== 'undefined' ? window : this);
